name: Tracker CI/CD

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*' 
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Загрузка кода
        uses: actions/checkout@v4

      - name: Настройка Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24' 

      - name: Загрузка зависимостей
        run: go mod download

      - name: Запуск тестов
        run: go test -v ./...

      - name: Проверка кода (Go Vet)
        run: go vet ./...


  publish:
    needs: test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Загрузка кода
        uses: actions/checkout@v4

      - name: Настройка Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Вход в Docker Hub
        uses: docker/login-action@v3
        with:
         
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Извлечение метаданных 
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: <sanzharss>/parcel-tracker

      - name: Сборка и публикация Docker-образа
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}